l_japanese:
 edict_nep_options_menu:0 "SEoOCメニュー"
 edict_nep_options_menu_desc:0 "このメニューを使用して、MOD"Some events of outside cluster"のイベントを設定したり、このmodのデバッグモードに入ったりします。" 
 
 nep_config.1.name:0 "SEoOCメニュー"
 nep_config.OK:0 "閉じる"
 nep_config.previous:0 "前のページ"
 
 nep_config.1.desc:0 "ここでは、MOD"Some events of outside cluster"のいくつかの設定を行うことができます。"
 nep_config.1.diff:0 "難易度"
 nep_config.1.wf:0 "イベント"ホワイトミスト"関連"
 nep_config.1.debug:0 "デバッグオプション"
 
 nep_config.2.desc.a:0 "今の難易度は：§Y通常§！"
 nep_config.2.desc.b:0 "今の難易度は：§G簡単§!\n §y1Mの艦隊を連続で生産できるほどのMODをプレイしていない限り、§!§R普通§!を選ばない。"
 nep_config.2.desc.c:0 "今の難易度は：§R困難§！"
 
 nep_config.2.easy:0 "簡単"
 nep_config.2.default:0 "普通"
 nep_config.2.desc.c:0 "困難"
 
 nep_config.3.desc.y:0 "イベント"ホワイトミスト"が発生する:§Gはい§!,いつ起きるかは自分で決めてできる"
 nep_config.3.desc.n:0 "イベント"ホワイトミスト"が発生する:§Rしない§!"
 nep_config.3.spawntime:0 "いつから?"
 nep_config.3.spawnmtth:0 "平均で何年か発生するか?"
 nep_config.3.y:0 "発生する."
 nep_config.3.n:0 "発生しない."
 nep_config.3.visual_effect:0 "パフォーマンスのために、白い霧の視覚効果をオフにします.(§R不可逆§!)"
 
 nep_config.3000.desc.2200:0 "ホワイトミストが発生するのは2200以降（つまりゲーム開始後）。"
 nep_config.3000.desc.2250:0 "ホワイトミストが発生するのは2250以降。"
 nep_config.3000.desc.2300:0 "ホワイトミストが発生するのは2300以降。"
 nep_config.3000.desc.2350:0 "ホワイトミストが発生するのは2350以降。"
 nep_config.3000.desc.2400:0 "ホワイトミストが発生するのは2400以降。"
 nep_config.3000.desc.midgame:0 "ホワイトミストが発生するのは中盤以降。"
 nep_config.3000.desc.endgame:0 "ホワイトミストが発生するのは終盤以降。"
 nep_config.3000.2200:0 "2200年以降に発生するに変更"
 nep_config.3000.2250:0 "2250年以降に発生するに変更"
 nep_config.3000.2300:0 "2300年以降に発生するに変更"
 nep_config.3000.2350:0 "2350年以降に発生するに変更"
 nep_config.3000.2400:0 "2400年以降に発生するに変更"
 nep_config.3000.midgame:0 "中盤以降に発生するに変更(デフォルト)"
 nep_config.3000.endgame:0 "終盤以降に発生するに変更"
 
 nep_config.3001.desc.15:0 "ホワイトミストの平均発生時間:§G15年§!"
 nep_config.3001.desc.40:0 "ホワイトミストの平均発生時間:§G40年§!"
 nep_config.3001.desc.110:0 "ホワイトミストの平均発生時間:§G110年§!"
 nep_config.3001.desc.225:0 "ホワイトミストの平均発生時間:§G225年§!"
 nep_config.3001.desc.470:0 "ホワイトミストの平均発生時間:§G470年§!"
 nep_config.3001.desc.1105:0 "ホワイトミストの平均発生時間:§G1105年§!"
 nep_config.3001.15:0 "15年."
 nep_config.3001.40:0 "40年."
 nep_config.3001.110:0 "110年."
 nep_config.3001.225:0 "225年."
 nep_config.3001.470:0 "470年."
 nep_config.3001.1105:0 "1105年." 
 
 nep_config.4.desc:0 "やりたいことを選択してください。"
 nep_config.4.highway:0 "ハイウェイ関連"
 nep_config.4.dragon:0 "ルェジンアクーアと七星竜のイベント関連"
 nep_config.4.orb:0 "オーブ関連"
 
 nep_config.4001.desc:0 "1.ハイウェイイベントを強制的に開始することができます。先駆文明イベントを完了しても、長い時間にトリガーされず場合にこのオプションを使用します。このオプションを使用するには、先駆文明の星系が発見されている必要があります。先駆文明の星系が発見されもこのオプションがない場合，SEoOCに対応していないMODを使用していることになりますので、作者に連絡して解決策を確認してください。\n2.ランダム調査船1隻を第1ステーション星系にテレポートさせる。もしあなたのワープ距離が足りないとき、このオプションを使用してお願いします。"
 nep_config.4001.highway.begin:0 "ハイウェイイベントを強制的に開始する"
 nep_config.4001.highway.warp:0 "ランダム調査船1隻を第1ステーション星系にテレポートする。" 
 
 nep_config.4002.desc:0 "1.ルェジンアクーアイベントを強制的に開始することができます。もし七角星系のすべての惑星を植民地化し、すべての渦をクリアしても、長い時間にトリガーされず時このオプションを使用します。また、他のMODで「竜の神殿」を壊してしまった場合にも使用することができます。  \n2.七星竜召喚:七星竜を召喚するために必要な条件をすべて与え、召喚のためのプロジェクトを再提供します。 このオプションを使用するには、七星竜が倒される必要があります。  \n3.七星竜強制召喚:全ての条件に関係なく七星竜を1体召喚する。このオプションを使用するには、七角星系が领有する必要があります。それでも出てこない場合は、④で弱化の七星竜を召喚してください。  \n4.弱化七星竜強制召喚。このドラゴンに "真竜降臨"を使用すると、消滅してしまうことがあります。"
 nep_config.4002.dragon.Legnahcras:0 "ルェジンアクーアイベントを強制的に開始する。"
 nep_config.4002.dragon.soft:0 "七星竜召喚。"
 nep_config.4002.dragon.hard:0 "七星竜強制召喚。"
 nep_config.4002.dragon.debuffed:0 "弱化七星竜強制召喚。" 
 
 nep_config.40020.desc.dragonnotend:0 "ドラゴンのイベントは終わっていないか、始まっていない。 下のオプションをクリックして、エピソードを完了またはスキップしてください。"
 nep_config.40020.desc.notsummoner:0 "あなたはドラゴンを召喚する資格はありません。下記のオプションを使って入手する。"
 nep_config.40020.desc.planetnotready:0 "あなたの七角星系の7つの惑星は、準備ができていません。 以下のオプションを使用して、強制的に準備する。"
 nep_config.40020.desc.ready:0 "このまま、召還竜プロジェクトを完了させてください。 ない場合は、以下のオプションで生成してください。"
  nep_config.40020.triggerfix0:0 "ドラゴンのイベントを強制終了"
 nep_config.40020.triggerfix1:0 "修复:召喚の資格"
 nep_config.40020.triggerfix2:0 "修复:竜の神殿とスターパワーを再生成。"
 nep_config.40020.redospecialproject:0 "召喚プロジェクトを生成する"
 
 nep_config.4003.desc.orb1:0 "あなたは今、オーブを1個持っています。 以下のオプションを使用して、起動可能な状態にします。 注：不特定の問題を引き起こす可能性があり、プロットを進めない場合があります。"
 nep_config.4003.desc.orb2:0 "あなたは今、オーブを2個持っています。 以下のオプションを使用して、起動可能な状態にします。 注：不特定の問題を引き起こす可能性があり、プロットを進めない場合があります。"
 nep_config.4003.desc.orb3:0 "あなたは今、オーブを3個持っています。 以下のオプションを使用して、起動可能な状態にします。 注：不特定の問題を引き起こす可能性があり、プロットを進めない場合があります。"
 nep_config.4003.desc.orb3useful:0 ""SEoOCのメインイベントを全て終了しました。 もうここでやることはない。"
 nep_config.4003.desc.noorbs:0 "まだオーブを持っていません。ここでやることはない"
 nep_config.4003.orb1:0 "起動します。"
 nep_config.4003.orb2:0 "起動します。"
 nep_config.4003.orb3:0 "起動します。"