l_russian:

 
 ##################################
 # A
 ##################################
 # ROOT = PLANET SCOPE
 # FROM = SHIP SCOPE
# [Root.GetStarName][Root.Owner.GetSpeciesAdj] [Root.Owner.GetSpeciesNamePlural][Root.GetRulerTitle][from.System.GetName]
# anomaly.211.c:0 "The safety of the [
 # anomaly.75.name:0 "Rock Brain"
 # anomaly.75.desc:0 "A scan of the particularly massive asteroid [From.GetName] yields fascinating results. The rock's core is shot through with a network of conductive crystals carrying a weak electric charge. The crew on the [Root.GetName] recognize this matrix as a primitive neural lattice and believe the celestial body to be thinking in some capacity, if not fully sapient. They seek permission to excavate the core and transport it to the nearest orbital station for closer study."
 # anomaly.75.a:0 "Make it so."
 # anomaly.75.b:0 "Make do with what you can study from the surface."
 # anomaly.75.b.tooltip:1 "Adds the §YRock Brain§! modifier to [From.GetName]:\n£physics£ §G+8§!"
 # anomaly.75.c:0 "It is not so unlike us. Let us talk."
 # anomaly.75.c.tooltip:0 "Order [Root.GetName] to attach surface probes to [From.GetName] and decode its alleged neural activity"
 # IS_LITHOID_EMPIRE_ICON_TIP:0 "This option is available due to §H[This.Owner.GetName]§! being a §YLithoid§! empire" # not a real trigger tooltip, used with icon = {}
 # uplift.7215.b.tooltip:1 "The [From.From.From.GetName] gain the §YAuthoritarian§! Ethic."
 # uplift.7215.c:0 "Self-realization comes only through independence."
 # uplift.7215.c.tooltip:1 "The [From.From.From.GetName] gain the §YEgalitarian§! Ethic."
 
 ##################################
 # GAME START
 ##################################
 
 shroud_rising_trigger.2.name:0 "Настройки мода: Восход Покрова"
 shroud_rising_trigger.2.desc:0 "Выберите вероятность возникновения кризисной цепочки §MОко ужаса§!. The choices represent an overall yearly chance of triggering the crisis once the requirements have been fulfilled.\n\n§RВы не сможете изменить это после начала игры.§!\n\nДля возникновения кризиса требуется как минимум одна нероботизированная/негештальт-угасшая империя или империя ИИ с псионическими основными расами."
 shroud_rising_trigger.2.a:0 "100%"
 shroud_rising_trigger.2.a.tooltip:0 "There will be a 100% chance the Eye of Terror crisis chain will occur."
 shroud_rising_trigger.2.b:0 "75%"
 shroud_rising_trigger.2.b.tooltip:0 "Every year there will be a 75% chance the Eye of Terror crisis chain will occur."
 shroud_rising_trigger.2.c:0 "50%"
 shroud_rising_trigger.2.c.tooltip:0 "Every year there will be a 50% chance the Eye of Terror crisis chain will occur."
 shroud_rising_trigger.2.d:0 "25%"
 shroud_rising_trigger.2.d.tooltip:0 "Every year there will be 25% chance the Eye of Terror crisis chain will occur."
 shroud_rising_trigger.2.e:0 "5%"
 shroud_rising_trigger.2.e.tooltip:0 "Every year there will be a 5% chance the Eye of Terror crisis chain will occur."
 shroud_rising_trigger.2.f:0 "§LDisabled§!"
 shroud_rising_trigger.2.f.tooltip:0 "The crisis will be disabled from spawning naturally, but you can always trigger it manually if you wish.\n\nCheck the mod page for more specific instructions."
 
 
 ##################################
 # MAIN MENU
 ##################################
 
 edict_shroud_rising_settings:0 "[MOD MENU] Восход Покрова"
 edict_shroud_rising_settings_desc:0 "Открыть текущие настройки для Восхода Покрова."
 
 shroud_rising_settings.1.name:0 "Настройки мода: Восход Покрова"
 shroud_rising_settings.1.desc:0 "Выберите опцию ниже, чтобы настроить свой опыт Восхода Покрова.\n\nЭти настройки могут быть открыты в любой момент во время прохождения игры через меню указов."
 shroud_rising_settings.1.a:0 "Настройки сложности"
 shroud_rising_settings.1.a.tooltip:0 "Отрегулируйте настройки сложности мода."
 shroud_rising_settings.1.b:0 "Выход."
 shroud_rising_settings.1.b.tooltip:0 "Закрыть меню."
 

 
 ##################################
 # DIFFICULTY
 ##################################
 
 shroud_rising_settings.2.name:0 "Настройки мода: Восход Покрова"
 shroud_rising_settings.2.1.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §LПо умолчанию§!"
 shroud_rising_settings.2.2.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P2x§!"
 shroud_rising_settings.2.3.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P3x§!"
 shroud_rising_settings.2.4.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P4x§!"
 shroud_rising_settings.2.5.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P5x§!"
 shroud_rising_settings.2.10.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P10x§!"
 shroud_rising_settings.2.25.desc:0 "Выберите общую силу £military_power£ кризиса из Восхода Покрова, это повлияет на появление врагов, которые появляются из Разломов, Ока Ужаса и других связанных событий.\n\nЭтот параметр можно изменить в любое время во время игры, и он не зависит от уровня сложности ванильного кризиса.\n\nТекущий выбор: §P25x§!\n\n'§TДа пребудет с тобой Сила.'"
 shroud_rising_settings.2.a:0 "§P25x§!"
 shroud_rising_settings.2.b:0 "§P10x§!"
 shroud_rising_settings.2.c:0 "§P5x§!"
 shroud_rising_settings.2.d:0 "§P4x§!"
 shroud_rising_settings.2.e:0 "§P3x§!"
 shroud_rising_settings.2.f:0 "§P2x§!"
 shroud_rising_settings.2.g:0 "§LПо умолчанию§!"
 shroud_rising_settings.2.h:0 "Главное меню"
 shroud_rising_settings.2.i:0 "Выход"
 
 
 sr_difficulty_2: "Сила x2"
 sr_difficulty_3: "Сила x3"
 sr_difficulty_4: "Сила x4"
 sr_difficulty_5:0 "Сила x5"
 sr_difficulty_10: "Сила x10"
 sr_difficulty_25:0 "Сила x25"