NDefines.NGraphics.GALAXY_STAR_ICON_SCALE	= 1.5
NDefines.NGraphics.GALAXY_STAR_ICON_MAX_SCALE = 1.25
NDefines.NGraphics.GALAXY_DUST_SIZE = 25.0
NDefines.NGraphics.GALAXY_DUST_SIZE_EXTRA = 35.0
NDefines.NGraphics.GALAXY_DUST_ROTATION_SPEED	= 0.0550
NDefines.NGraphics.GALAXY_NEBULA_DUST_SIZE = 25.0
NDefines.NGraphics.GALAXY_NEBULA_DUST_SIZE_EXTRA = 29.0
NDefines.NGraphics.GALAXY_NEBULA_DUST_ROTATION_SPEED  = 0.120
NDefines.NGraphics.TRAILS_ALPHA_FADE  = 1.0 -- Controls of quick we alpha fade-out
NDefines.NGraphics.TRAILS_MISSILE_ALPHA_FADE  = 6 -- Controls of quick we alpha fade-out missile trails
NDefines.NGraphics.TRAILS_BASE_WIDTH	= 0.7 -- Trails width
NDefines.NGraphics.TRAILS_MISSILE_BASE_WIDTH	= 3.0 -- Missile trails width
NDefines.NGraphics.TRAILS_LOCATOR_NAME	= "exhaust"
NDefines.NGraphics.STRIKE_CRAFT_TRAIL_FADE_RATE	= 0.5
NDefines.NGraphics.BORDER_FLAG_SCALE	= 0.6
NDefines.NGraphics.MAPNAME_BORDER_SCALE	= 1.0
NDefines.NGraphics.MAPNAME_BORDER_MIN_SIZE = 100
NDefines.NGraphics.MAPNAME_BORDER_OFFSET_MUL	= 0.75
NDefines.NGraphics.MAPNAME_BORDER_OFFSET_ADD	= 4.0
NDefines.NGraphics.MAPNAME_NEBULA_SCALE	= 1.8
NDefines.NGraphics.MAPNAME_SECTOR_SCALE	= 9
