l_english:
 edict_nep_options_menu:0 "SEoOC Config Bar"
 edict_nep_options_menu_desc:0 "Use this menu to config or debug the events of SEoOC."
 
 nep_config.1.name:0 "SEoOC Config Bar"
 nep_config.OK:0 "Close"
 nep_config.previous:0 "Previous"
 
 nep_config.1.desc:0 "Here you can config some options of mod SEoOC."
 nep_config.1.diff:0 "Difficulty"
 nep_config.1.wf:0 "White Goo Options"
 nep_config.1.debug:0 "Debug Options"
 
 nep_config.2.desc.a:0 "Now difficulty is:§YDefault§!"
 nep_config.2.desc.b:0 "Now difficulty is:§GEasy§!\n §YDon't choose §RDefault§! if your mods don't support you make a fleet with 1 million fire power!§!"
 nep_config.2.desc.c:0 "Now difficulty is:§RHard§!"
 
 nep_config.2.easy:0 "Easy"
 nep_config.2.default:0 "Default"
 nep_config.2.hard:0 "Hard"
 
 nep_config.3.desc.y:0 "Now White Goo event can be spawn:§GYes§!,you can choose what time it will spawn."
 nep_config.3.desc.n:0 "Now White Goo event can be spawn:§RNo§!"
 nep_config.3.spawntime:0 "Spawn After what time?"
 nep_config.3.spawnmtth:0 "Mean Time to Happen is?"
 nep_config.3.y:0 "Make it can spawn."
 nep_config.3.n:0 "Make it not to spawn."
 nep_config.3.visual_effect:0 "Close all visual effect of white goo.(§RIrreversible§!)"
 
 nep_config.3000.desc.2200:0 "Now White Goo will spawn after year 2200(Means always).Want to change it?"
 nep_config.3000.desc.2250:0 "Now White Goo will spawn after year 2250.Want to change it?"
 nep_config.3000.desc.2300:0 "Now White Goo will spawn after year 2300.Want to change it?"
 nep_config.3000.desc.2350:0 "Now White Goo will spawn after year 2350.Want to change it?"
 nep_config.3000.desc.2400:0 "Now White Goo will spawn after year 2400.Want to change it?"
 nep_config.3000.desc.midgame:0 "Now White Goo will spawn after Mid-Game.Want to change it?"
 nep_config.3000.desc.endgame:0 "Now White Goo will spawn after End-Game.Want to change it?"
 nep_config.3000.2200:0 "After 2200"
 nep_config.3000.2250:0 "After 2250"
 nep_config.3000.2300:0 "After 2300"
 nep_config.3000.2350:0 "After 2350"
 nep_config.3000.2400:0 "After 2400"
 nep_config.3000.midgame:0 "After Mid-Game(Default)"
 nep_config.3000.endgame:0 "After End-Game"
 
 nep_config.3001.desc.15:0 "Now MTTH of White Goo event is:§G15 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.desc.40:0 "Now MTTH of White Goo event is:§G40 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.desc.110:0 "Now MTTH of White Goo event is:§G110 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.desc.225:0 "Now MTTH of White Goo event is:§G225 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.desc.470:0 "Now MTTH of White Goo event is:§G470 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.desc.1105:0 "Now MTTH of White Goo event is:§G1105 years§!(MTTH means how long, on average, event begins.It MAY begin in the second year,or never happen before you end this game.)"
 nep_config.3001.15:0 "15 years."
 nep_config.3001.40:0 "40 years."
 nep_config.3001.110:0 "110 years."
 nep_config.3001.225:0 "225 years."
 nep_config.3001.470:0 "470 years."
 nep_config.3001.1105:0 "1105 years." 
 
 nep_config.4.desc:0 "Choose what you want to do."
 nep_config.4.highway:0 "Highways events"
 nep_config.4.dragon:0 "Legnahcras and Dragon events"
 nep_config.4.orb:0 "Orbs" 
 
 nep_config.4001.desc:0 "You can do here:\n1.Begin highway events if it don't trigger right.You need to have found one precursor system first.\n2.Warp random of your science ship to first highway station system,for whom can't reach it even with psi-jump drive."
 nep_config.4001.highway.begin:0 "Begin highway events."
 nep_config.4001.highway.warp:0 "Warp random of your science ship to first highway station."
 
 nep_config.4002.desc:0 "You can do here:\n1.Begin Legnahcras event.You need have occupy all seven planets,but not need temples.If you occupy all seven planets,cleared all blocker,and wait a long time but nothing happened,use this.\n2.Summon a dragon in a "soft" way:Give all triggers you need,then begin a project.You need to occupy all seven planets.Use this when you can't trigger a project to summon dragon.\n3.Summon a dragon in a "hard" way.All conditions will be ignore.You need to occupy all seven planets.Use this if you don't trigger project even use 2.option,or after you complete project,dragon not appear.If fails,maybe your mods are too strong.Try 4.options to get a debuffed dragon.\n4.Get a debuffed dragon.Caution:It MAY vanished by Perfection project."
 nep_config.4002.dragon.Legnahcras:0 "Begin Legnahcras event."
 nep_config.4002.dragon.soft:0 "Summon a dragon in a "soft" way."
 nep_config.4002.dragon.hard:0 "Summon a dragon in a "hard" way."
 nep_config.4002.dragon.debuffed:0 "Summon a debuffed dragon in a hard way."
 
 nep_config.40020.desc.dragonnotend:0 "Dragon events not end or not begin.End or skip it using option below."
 nep_config.40020.desc.notsummoner:0 "You aren't dragon summoner now.Get it using option below."
 nep_config.40020.desc.planetnotready:0 "Your seven planets not ready.Make it ready option below."
 nep_config.40020.desc.ready:0 "You can complete project to summon dragons now.If project not exists,use option below."
 nep_config.40020.triggerfix0:0 "Trigger fix:End Dragon events"
 nep_config.40020.triggerfix1:0 "Trigger fix:Dragon Summoner"
 nep_config.40020.triggerfix2:0 "Trigger fix:Seven planets get buff modifier and temple."
 nep_config.40020.redospecialproject:0 "Re spawn special project." 
 
 nep_config.4003.desc.orb1:0 "Now you have 1 orb.Make it activable using option below.Caution:MAY cause unknown problems."
 nep_config.4003.desc.orb2:0 "Now you have 2 orbs.Make them activable using option below.Caution:MAY cause unknown problems."
 nep_config.4003.desc.orb3:0 "Now you have 3 orbs.Make them activable using option below.Caution:MAY cause unknown problems."
 nep_config.4003.desc.orb3useful:0 "You have complete all main-line of SEoOC.Nothing to do here now."
 nep_config.4003.desc.noorbs:0 "You don't have any orbs.Nothing to do here now."
 nep_config.4003.orb1:0 "Make it activable."
 nep_config.4003.orb2:0 "Make them activable."
 nep_config.4003.orb3:0 "Make them activable."