l_simp_chinese:
 edict_nep_options_menu:0 "SEoOC菜单"
 edict_nep_options_menu_desc:0 "用这个菜单配置SEoOC这个mod的事件或者进入这个mod的debug模式。" 
 
 nep_config.1.name:0 "SEoOC菜单"
 nep_config.OK:0 "关闭"
 nep_config.previous:0 "上一页"
 
 nep_config.1.desc:0 "在这里你可以对SEoOC这个mod进行一些配置。"
 nep_config.1.diff:0 "难度"
 nep_config.1.wf:0 "白雾相关"
 nep_config.1.debug:0 "Debug选项"
 
 nep_config.2.desc.a:0 "现在的难度是：§Y普通§!"
 nep_config.2.desc.b:0 "现在的难度是：§G简单§!\n §Y不要选§R普通§!除非你打的mod足够支持你生产1M一队的舰队§!"
 nep_config.2.desc.c:0 "现在的难度是：§R困难§!"
 
 nep_config.2.easy:0 "简单"
 nep_config.2.default:0 "普通"
 nep_config.2.hard:0 "困难"
 
 nep_config.3.desc.y:0 "白雾剧情是否可发生:§G是§!,你可以选择什么时候发生."
 nep_config.3.desc.n:0 "白雾剧情是否可发生:§R否§!"
 nep_config.3.spawntime:0 "从什么时候开始可发生?"
 nep_config.3.spawnmtth:0 "平均要多少年发生?"
 nep_config.3.y:0 "让白雾剧情可发生."
 nep_config.3.n:0 "让白雾剧情不可发生."
 nep_config.3.visual_effect:0 "关闭白雾的视觉效果以减缓卡机.(§R不可逆§!)"
 
 nep_config.3000.desc.2200:0 "白雾将会发生在2200年后(也就是开始游戏后)。"
 nep_config.3000.desc.2250:0 "白雾将会发生在2250年后。"
 nep_config.3000.desc.2300:0 "白雾将会发生在2300年后。"
 nep_config.3000.desc.2350:0 "白雾将会发生在2350年后。"
 nep_config.3000.desc.2400:0 "白雾将会发生在2400年后。"
 nep_config.3000.desc.midgame:0 "白雾将会发生在进入游戏中期后。"
 nep_config.3000.desc.endgame:0 "白雾将会发生在进入游戏末期后。"
 nep_config.3000.2200:0 "改为2200后发生"
 nep_config.3000.2250:0 "改为2250后发生"
 nep_config.3000.2300:0 "改为2300后发生"
 nep_config.3000.2350:0 "改为2350后发生"
 nep_config.3000.2400:0 "改为2400后发生"
 nep_config.3000.midgame:0 "改为进入游戏中期后(默认选项)"
 nep_config.3000.endgame:0 "改为进入游戏末期后"
 
 nep_config.3001.desc.15:0 "现在白雾剧情的平均发生时间是:§G15年§!"
 nep_config.3001.desc.40:0 "现在白雾剧情的平均发生时间是:§G40年§!"
 nep_config.3001.desc.110:0 "现在白雾剧情的平均发生时间是:§G110年§!"
 nep_config.3001.desc.225:0 "现在白雾剧情的平均发生时间是:§G225年§!"
 nep_config.3001.desc.470:0 "现在白雾剧情的平均发生时间是:§G470年§!"
 nep_config.3001.desc.1105:0 "现在白雾剧情的平均发生时间是:§G1105年§!"
 nep_config.3001.15:0 "15年."
 nep_config.3001.40:0 "40年."
 nep_config.3001.110:0 "110年."
 nep_config.3001.225:0 "225年."
 nep_config.3001.470:0 "470年."
 nep_config.3001.1105:0 "1105年." 
 
 nep_config.4.desc:0 "请选择你要做什么。"
 nep_config.4.highway:0 "高速路相关"
 nep_config.4.dragon:0 "使天众与龙相关"
 nep_config.4.orb:0 "宝玉相关"
 
 nep_config.4001.desc:0 "你能够:\n1.强制开始高速路剧情，如果你完成了先驱者剧情却等待很久都没有触发的话使用该选项。必须要发现一个先驱者星系才能使用该选项。如果你发现了先驱者星系却依然没有该选项，如果你没有错误理解先驱者星系的意义，那就是你使用的mod里存在不兼容SEoOC的，请联系作者看看是否有解决办法。\n2.传送你的随机一艘科研船到第一站星系。用于打了mod导致星系结构太过奇怪，跃迁过不去的情况下。"
 nep_config.4001.highway.begin:0 "强制开始高速路剧情"
 nep_config.4001.highway.warp:0 "传送随机科研船到第一“站”星系。" 
 
 nep_config.4002.desc:0 "你能够:\n1.强制开始使天众剧情。如果你殖民了七边形的所有星球且清了漩涡建了奉龙殿但却等很久都没动静，可以使用该选项。也可用于使用其他mod把奉龙殿拆掉了的情况下。\n2.“软”召唤龙:给予召唤龙所需要的所有条件，并且重新提供召唤用的project。必须先打败敌对的龙。\n3.“硬”召唤龙：无视所有条件召唤一只龙。必须先占领7个星系。如果使用该选项龙依然出不来，请使用第4选项召唤一只弱化的龙。\n4.召唤一只弱化的龙。注意：如果你对这只龙使用真龙降临，可能会导致直接消失。"
 nep_config.4002.dragon.Legnahcras:0 "强制开始使天众剧情。"
 nep_config.4002.dragon.soft:0 "“软”召唤龙。"
 nep_config.4002.dragon.hard:0 "“硬”召唤龙。"
 nep_config.4002.dragon.debuffed:0 "召唤一只弱化的龙。" 
 
 nep_config.40020.desc.dragonnotend:0 "屠龙的剧情没有做完或者没有开始。点击下面选项完成或者跳过该剧情。"
 nep_config.40020.desc.notsummoner:0 "你没有召唤龙的资格。使用下面的选项获取。"
 nep_config.40020.desc.planetnotready:0 "你的七边形的7个星球未准备好。使用下面的选项强制准备。"
 nep_config.40020.desc.ready:0 "你可以去完成召唤龙的项目了。没有的话，使用下面的选项生成。"
 nep_config.40020.triggerfix0:0 "强行结束剧情"
 nep_config.40020.triggerfix1:0 "修复:召唤资格"
 nep_config.40020.triggerfix2:0 "修复:七个星球取得星之力跟奉龙殿。"
 nep_config.40020.redospecialproject:0 "生成召唤项目"
 
 nep_config.4003.desc.orb1:0 "你现在有1个宝玉.使用下面的选项让其可发动。注意：可能会导致不明问题，也不一定能推进剧情。"
 nep_config.4003.desc.orb2:0 "你现在有2个宝玉.使用下面的选项让其可发动。注意：可能会导致不明问题，也不一定能推进剧情。"
 nep_config.4003.desc.orb3:0 "你现在有3个宝玉.使用下面的选项让其可发动。注意：可能会导致不明问题，也不一定能推进剧情。"
 nep_config.4003.desc.orb3useful:0 "你已经完成了SEoOC的全部主线。这里没有什么可做的事情了。"
 nep_config.4003.desc.noorbs:0 "你还没搞到宝玉。没有什么可做的事情。"
 nep_config.4003.orb1:0 "启动。"
 nep_config.4003.orb2:0 "启动。"
 nep_config.4003.orb3:0 "启动。"